version: "2"
services:
  scrapyd:
    container_name: scrapyd-{{cookiecutter.project_slug}}
    image: alexandresgf/scrapyd-service:{{cookiecutter.scrapyd_service_version}}
    environment:
      SCRAPYD_PROJECT_NAME: {{cookiecutter.project_slug}}
    ports:
      - 6800:6800
    volumes:
      - .:${HOME}/{{cookiecutter.project_slug}}
    networks:
      - {{cookiecutter.project_slug}}net
  mongo:
    container_name: mongo-{{cookiecutter.project_slug}}
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - {{cookiecutter.project_slug}}net

networks:
  {{cookiecutter.project_slug}}net:
    driver: bridge
